server:
  servlet:
    context-path: /api/v1

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID:default-client-id}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:default-client-secret}
            scope:
              - openid
              - profile
              - email
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    github.muhsenerdev: TRACE
    org.springframework.security: DEBUG

app:
  users:
    requirements:
      username-required: false
      name-required: false
    watchdog:
      registration-cleanup-interval: 5m
    admin:
      email: ${ADMIN_EMAIL:admin@admin.com}
      password: ${ADMIN_PASSWORD:admin123}
  security:
    jwt:
      secret: "default_secret_key_at_least_32_chars_long_!!"
      expiration: 3600000
    access-token:
      cookie:
        name: access_token
        http-only: true
        secure: false
        path: /
    csrf:
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN
      http-only: false
      secure: false
      cookie-path: /
      domain: localhost
      same-site: Lax