plans:
  core-features:
    - code: "TALK_MINUTES"
      name: "Konuşma Dakikası"
      type: "QUOTA"
    - code: "AI_REWRITE"
      name: "AI Metin Düzenleme"
      type: "BOOLEAN"
    - code: "PRIVATE_ROOM"
      name: "Özel Oda Erişimi"
      type: "BOOLEAN"
